// Writes the app assets of Zanance from the approved master (geometry ffae7f2ee01a0705, owner approval 2026-09-28,
// decision D-26): launcher icon (background + foreground), splash screens, in-app images, the Android notification icon
// and the Android 13+ themed (monochrome) icon. Run after build.mjs:  node integrate.mjs
// Only these files in the app are written; the geometry is never redrawn.
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { dirname } from 'node:path';
import { framedSvg, lockupSvg, symbolSvg } from './lib/svg.mjs';
import { wordmarkPath } from './lib/formats.mjs';

const APP = '../../../src/Apps/Zanance/Vafadar.Zanance.App';
const APPROVED_GEOMETRY = 'ffae7f2ee01a0705';
const BACKGROUND = '#F4F6F8'; // neutral light (owner choice)
const TEXT = '#111827';

const geometryJson = readFileSync('../source/geometry.json', 'utf8');
const geometryHash = createHash('sha256').update(geometryJson).digest('hex').slice(0, 16);
if (geometryHash !== APPROVED_GEOMETRY) throw new Error(`geometry ${geometryHash} is not the approved ${APPROVED_GEOMETRY}; approve it first`);
const geometry = JSON.parse(geometryJson);
const [W, H] = geometry.size;

const written = [];
function write(rel, content) {
  const path = `${APP}/${rel}`; mkdirSync(dirname(path), { recursive: true }); writeFileSync(path, content);
  written.push({ path: `src/Apps/Zanance/Vafadar.Zanance.App/${rel}`, sha256: createHash('sha256').update(content).digest('hex') });
}
const clean = svg => svg.replace(/<!--[\s\S]*?-->\n/, `<!-- Zanance – generated by branding/zanance/scripts/integrate.mjs from the approved master (geometry ${APPROVED_GEOMETRY}). Do not edit by hand. -->\n`);

// Farthest silhouette point from the symbol centre, to keep the symbol inside circular safe zones.
const pts = [...geometry.silhouette.matchAll(/(-?\d*\.?\d+) (-?\d*\.?\d+)/g)].map(m => [parseFloat(m[1]), parseFloat(m[2])]);
const radius = Math.max(...pts.map(([x, y]) => Math.hypot(x - W / 2, y - H / 2)));
const fillForRadius = r => (r * Math.max(W, H)) / radius; // symbol side (fraction of canvas) with its far point at r

// 1. Launcher icon. Android adaptive: 108 dp canvas, safe circle 66 dp → far point at 33/108. iOS and Windows get the
//    same foreground scaled up by ForegroundScale in the project file (no mask safe zone there).
write('Resources/AppIcon/appicon.svg', `<?xml version="1.0" encoding="UTF-8"?>\n<!-- Zanance launcher icon background (neutral light, D-26). -->\n<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 456 456" width="456" height="456"><rect width="456" height="456" fill="${BACKGROUND}"/></svg>\n`);
write('Resources/AppIcon/appiconfg.svg', clean(framedSvg(geometry, { side: 456, fill: fillForRadius(33 / 108), geometryHash })));

// 2. Splash. Android 12+ shows the splash image inside a circle of 2/3 of its size: symbol only, far point at 1/3.
//    iOS and Windows show the image as is: symbol + wordmark (owner choice), wordmark as outlines.
write('Resources/Splash/splash.svg', clean(framedSvg(geometry, { side: 456, fill: fillForRadius(1 / 3) * 0.96, geometryHash })));
const wm = wordmarkPath('urbanist', 'Zanance', 1000);
const lockup = clean(lockupSvg(geometry, wm, { textColor: TEXT, geometryHash }));
write('Resources/Splash/splashlockup.svg', lockup);
const lockupWidth = parseFloat(/viewBox="0 0 ([\d.]+) /.exec(lockup)[1]);

// 3. In-app images (MauiImage): the colour symbol, and the mono white symbol for dark surfaces if ever needed.
write('Resources/Images/zanance_symbol.svg', clean(symbolSvg(geometry, { variant: 'color', geometryHash })));

// 4. Android: notification small icon (white silhouette, 24 dp; the status bar uses only its alpha).
const vectorDrawable = (size, viewport, fill) => {
  const s = (viewport * fill) / Math.max(W, H); const tx = (viewport - W * s) / 2, ty = (viewport - H * s) / 2;
  return `<?xml version="1.0" encoding="utf-8"?>
<!-- Zanance – generated by branding/zanance/scripts/integrate.mjs from the approved master (geometry ${APPROVED_GEOMETRY}). -->
<vector xmlns:android="http://schemas.android.com/apk/res/android" android:width="${size}dp" android:height="${size}dp" android:viewportWidth="${viewport}" android:viewportHeight="${viewport}">
  <group android:translateX="${tx.toFixed(3)}" android:translateY="${ty.toFixed(3)}" android:scaleX="${s.toFixed(5)}" android:scaleY="${s.toFixed(5)}">
    <path android:fillColor="#FFFFFFFF" android:fillType="evenOdd" android:pathData="${geometry.silhouette}"/>
  </group>
</vector>
`;
};
write('Platforms/Android/Resources/drawable/ic_stat_zanance.xml', vectorDrawable(24, 24, 20 / 24)); // 20 dp live area of 24
// The themed (monochrome) icon of Android 13+ needs no extra file: the adaptive icon MAUI generates uses the foreground
// as its monochrome layer, and Android takes only its alpha – which is exactly the symbol's silhouette.

writeFileSync('../reports/integration.json', JSON.stringify({
  approvedGeometry: APPROVED_GEOMETRY, background: BACKGROUND,
  layout: { adaptiveForegroundFill: +fillForRadius(33 / 108).toFixed(4), androidSplashFill: +(fillForRadius(1 / 3) * 0.96).toFixed(4), lockupViewBox: [Number(lockupWidth.toFixed(3)), H] },
  wordmark: { font: wm.fontName, version: wm.fontVersion, license: wm.license },
  written,
}, null, 1) + '\n');
console.log(written.length, 'files; lockup aspect', (lockupWidth / H).toFixed(3), '; adaptive fill', fillForRadius(33 / 108).toFixed(3));
