blank_issues_enabled: false
contact_links:
  - name: Report a security vulnerability
    url: https://docs.github.com/code-security/security-advisories/guidance-on-reporting-and-writing-information-about-vulnerabilities/privately-reporting-a-security-vulnerability
    about: Please report security issues privately through GitHub's "Report a vulnerability" button in the Security tab.
