// <auto-generated />
using System;
using System.Reflection;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Vafadar.Core.Domain;
using Vafadar.Data.Conventions;
using Vafadar.Zanance.Core.Forecasts;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Vafadar.Zanance.Data.CompiledModel
{
    [EntityFrameworkInternal]
    public partial class ForecastSnapshotEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "Vafadar.Zanance.Core.Forecasts.ForecastSnapshot",
                typeof(ForecastSnapshot),
                baseEntityType,
                propertyCount: 14,
                unnamedIndexCount: 1,
                keyCount: 1);

            var id = runtimeEntityType.AddProperty(
                "Id",
                typeof(Guid),
                propertyInfo: typeof(Entity).GetProperty("Id", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Entity).GetField("<Id>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueGenerated: ValueGenerated.OnAdd,
                afterSaveBehavior: PropertySaveBehavior.Throw,
                sentinel: new Guid("00000000-0000-0000-0000-000000000000"));

            var accountIds = runtimeEntityType.AddProperty(
                "AccountIds",
                typeof(string),
                propertyInfo: typeof(ForecastSnapshot).GetProperty("AccountIds", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ForecastSnapshot).GetField("<AccountIds>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));

            var appVersion = runtimeEntityType.AddProperty(
                "AppVersion",
                typeof(string),
                propertyInfo: typeof(ForecastSnapshot).GetProperty("AppVersion", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ForecastSnapshot).GetField("<AppVersion>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 40);

            var assumptions = runtimeEntityType.AddProperty(
                "Assumptions",
                typeof(string),
                propertyInfo: typeof(ForecastSnapshot).GetProperty("Assumptions", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ForecastSnapshot).GetField("<Assumptions>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 2000);

            var baseDate = runtimeEntityType.AddProperty(
                "BaseDate",
                typeof(DateOnly),
                propertyInfo: typeof(ForecastSnapshot).GetProperty("BaseDate", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ForecastSnapshot).GetField("<BaseDate>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: new DateOnly(1, 1, 1));

            var createdAt = runtimeEntityType.AddProperty(
                "CreatedAt",
                typeof(DateTimeOffset),
                propertyInfo: typeof(ForecastSnapshot).GetProperty("CreatedAt", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ForecastSnapshot).GetField("<CreatedAt>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueConverter: new UtcTicksDateTimeOffsetConverter());
            createdAt.SetSentinelFromProviderValue(0L);

            var currencyCode = runtimeEntityType.AddProperty(
                "CurrencyCode",
                typeof(string),
                propertyInfo: typeof(ForecastSnapshot).GetProperty("CurrencyCode", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ForecastSnapshot).GetField("<CurrencyCode>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 3);

            var horizon = runtimeEntityType.AddProperty(
                "Horizon",
                typeof(DateOnly),
                propertyInfo: typeof(ForecastSnapshot).GetProperty("Horizon", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ForecastSnapshot).GetField("<Horizon>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: new DateOnly(1, 1, 1));

            var minimum = runtimeEntityType.AddProperty(
                "Minimum",
                typeof(long),
                propertyInfo: typeof(ForecastSnapshot).GetProperty("Minimum", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ForecastSnapshot).GetField("<Minimum>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0L);

            var minimumDate = runtimeEntityType.AddProperty(
                "MinimumDate",
                typeof(DateOnly),
                propertyInfo: typeof(ForecastSnapshot).GetProperty("MinimumDate", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ForecastSnapshot).GetField("<MinimumDate>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: new DateOnly(1, 1, 1));

            var name = runtimeEntityType.AddProperty(
                "Name",
                typeof(string),
                propertyInfo: typeof(ForecastSnapshot).GetProperty("Name", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ForecastSnapshot).GetField("<Name>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 100);

            var path = runtimeEntityType.AddProperty(
                "Path",
                typeof(string),
                propertyInfo: typeof(ForecastSnapshot).GetProperty("Path", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ForecastSnapshot).GetField("<Path>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));

            var unknownCount = runtimeEntityType.AddProperty(
                "UnknownCount",
                typeof(int),
                propertyInfo: typeof(ForecastSnapshot).GetProperty("UnknownCount", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ForecastSnapshot).GetField("<UnknownCount>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);

            var updatedAt = runtimeEntityType.AddProperty(
                "UpdatedAt",
                typeof(DateTimeOffset),
                propertyInfo: typeof(ForecastSnapshot).GetProperty("UpdatedAt", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ForecastSnapshot).GetField("<UpdatedAt>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueConverter: new UtcTicksDateTimeOffsetConverter());
            updatedAt.SetSentinelFromProviderValue(0L);

            var key = runtimeEntityType.AddKey(
                new[] { id });
            runtimeEntityType.SetPrimaryKey(key);

            var index = runtimeEntityType.AddIndex(
                new[] { createdAt });

            return runtimeEntityType;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", null);
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "ForecastSnapshots");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
