// <auto-generated />
using System;
using System.Reflection;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Vafadar.Zanance.Core.Budgets;
using Vafadar.Zanance.Core.Plans;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Vafadar.Zanance.Data.CompiledModel
{
    [EntityFrameworkInternal]
    public partial class RecurrenceRuleEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "Vafadar.Zanance.Core.Plans.RecurrenceRule",
                typeof(RecurrenceRule),
                baseEntityType,
                propertyCount: 14,
                foreignKeyCount: 1,
                keyCount: 1);

            var scheduleId = runtimeEntityType.AddProperty(
                "ScheduleId",
                typeof(Guid),
                afterSaveBehavior: PropertySaveBehavior.Throw,
                sentinel: new Guid("00000000-0000-0000-0000-000000000000"));

            var calendar = runtimeEntityType.AddProperty(
                "Calendar",
                typeof(PeriodCalendar),
                propertyInfo: typeof(RecurrenceRule).GetProperty("Calendar", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(RecurrenceRule).GetField("<Calendar>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            calendar.SetSentinelFromProviderValue(0);
            calendar.AddAnnotation("Relational:ColumnName", "Calendar");

            var count = runtimeEntityType.AddProperty(
                "Count",
                typeof(int?),
                propertyInfo: typeof(RecurrenceRule).GetProperty("Count", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(RecurrenceRule).GetField("<Count>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            count.AddAnnotation("Relational:ColumnName", "Count");

            var dayRule = runtimeEntityType.AddProperty(
                "DayRule",
                typeof(MonthDayRule),
                propertyInfo: typeof(RecurrenceRule).GetProperty("DayRule", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(RecurrenceRule).GetField("<DayRule>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            dayRule.SetSentinelFromProviderValue(0);
            dayRule.AddAnnotation("Relational:ColumnName", "DayRule");

            var end = runtimeEntityType.AddProperty(
                "End",
                typeof(EndKind),
                propertyInfo: typeof(RecurrenceRule).GetProperty("End", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(RecurrenceRule).GetField("<End>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            end.SetSentinelFromProviderValue(0);
            end.AddAnnotation("Relational:ColumnName", "EndKind");

            var endDate = runtimeEntityType.AddProperty(
                "EndDate",
                typeof(DateOnly?),
                propertyInfo: typeof(RecurrenceRule).GetProperty("EndDate", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(RecurrenceRule).GetField("<EndDate>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            endDate.AddAnnotation("Relational:ColumnName", "EndDate");

            var frequency = runtimeEntityType.AddProperty(
                "Frequency",
                typeof(Frequency),
                propertyInfo: typeof(RecurrenceRule).GetProperty("Frequency", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(RecurrenceRule).GetField("<Frequency>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            frequency.SetSentinelFromProviderValue(0);
            frequency.AddAnnotation("Relational:ColumnName", "Frequency");

            var holidayRegion = runtimeEntityType.AddProperty(
                "HolidayRegion",
                typeof(string),
                propertyInfo: typeof(RecurrenceRule).GetProperty("HolidayRegion", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(RecurrenceRule).GetField("<HolidayRegion>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 8);
            holidayRegion.AddAnnotation("Relational:ColumnName", "HolidayRegion");

            var interval = runtimeEntityType.AddProperty(
                "Interval",
                typeof(int),
                propertyInfo: typeof(RecurrenceRule).GetProperty("Interval", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(RecurrenceRule).GetField("<Interval>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            interval.AddAnnotation("Relational:ColumnName", "Interval");

            var missingDay = runtimeEntityType.AddProperty(
                "MissingDay",
                typeof(MissingDayPolicy),
                propertyInfo: typeof(RecurrenceRule).GetProperty("MissingDay", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(RecurrenceRule).GetField("<MissingDay>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            missingDay.SetSentinelFromProviderValue(0);
            missingDay.AddAnnotation("Relational:ColumnName", "MissingDay");

            var secondDay = runtimeEntityType.AddProperty(
                "SecondDay",
                typeof(int?),
                propertyInfo: typeof(RecurrenceRule).GetProperty("SecondDay", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(RecurrenceRule).GetField("<SecondDay>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            secondDay.AddAnnotation("Relational:ColumnName", "SecondDay");

            var start = runtimeEntityType.AddProperty(
                "Start",
                typeof(DateOnly),
                propertyInfo: typeof(RecurrenceRule).GetProperty("Start", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(RecurrenceRule).GetField("<Start>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: new DateOnly(1, 1, 1));
            start.AddAnnotation("Relational:ColumnName", "Start");

            var weekendDays = runtimeEntityType.AddProperty(
                "WeekendDays",
                typeof(int),
                propertyInfo: typeof(RecurrenceRule).GetProperty("WeekendDays", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(RecurrenceRule).GetField("<WeekendDays>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            weekendDays.AddAnnotation("Relational:ColumnName", "WeekendDays");

            var weekendShift = runtimeEntityType.AddProperty(
                "WeekendShift",
                typeof(WeekendShift),
                propertyInfo: typeof(RecurrenceRule).GetProperty("WeekendShift", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(RecurrenceRule).GetField("<WeekendShift>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            weekendShift.SetSentinelFromProviderValue(0);
            weekendShift.AddAnnotation("Relational:ColumnName", "WeekendShift");

            var key = runtimeEntityType.AddKey(
                new[] { scheduleId });
            runtimeEntityType.SetPrimaryKey(key);

            return runtimeEntityType;
        }

        public static RuntimeForeignKey CreateForeignKey1(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType)
        {
            var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("ScheduleId") },
                principalEntityType.FindKey(new[] { principalEntityType.FindProperty("Id") }),
                principalEntityType,
                deleteBehavior: DeleteBehavior.Cascade,
                unique: true,
                required: true,
                requiredDependent: true,
                ownership: true);

            var rule = principalEntityType.AddNavigation("Rule",
                runtimeForeignKey,
                onDependent: false,
                typeof(RecurrenceRule),
                propertyInfo: typeof(Schedule).GetProperty("Rule", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Schedule).GetField("<Rule>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                eagerLoaded: true);

            return runtimeForeignKey;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", null);
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "Schedules");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
