// <auto-generated />
using System;
using System.Reflection;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Vafadar.Core.Domain;
using Vafadar.Data.Conventions;
using Vafadar.Zanance.Core.Ledger;
using Vafadar.Zanance.Core.Plans;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Vafadar.Zanance.Data.CompiledModel
{
    [EntityFrameworkInternal]
    public partial class ScheduleEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "Vafadar.Zanance.Core.Plans.Schedule",
                typeof(Schedule),
                baseEntityType,
                propertyCount: 30,
                navigationCount: 1,
                foreignKeyCount: 3,
                unnamedIndexCount: 3,
                keyCount: 1);

            var id = runtimeEntityType.AddProperty(
                "Id",
                typeof(Guid),
                propertyInfo: typeof(Entity).GetProperty("Id", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Entity).GetField("<Id>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueGenerated: ValueGenerated.OnAdd,
                afterSaveBehavior: PropertySaveBehavior.Throw,
                sentinel: new Guid("00000000-0000-0000-0000-000000000000"));

            var accountId = runtimeEntityType.AddProperty(
                "AccountId",
                typeof(Guid),
                propertyInfo: typeof(Schedule).GetProperty("AccountId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Schedule).GetField("<AccountId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: new Guid("00000000-0000-0000-0000-000000000000"));

            var activeFrom = runtimeEntityType.AddProperty(
                "ActiveFrom",
                typeof(DateOnly?),
                propertyInfo: typeof(Schedule).GetProperty("ActiveFrom", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Schedule).GetField("<ActiveFrom>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);

            var activeUntil = runtimeEntityType.AddProperty(
                "ActiveUntil",
                typeof(DateOnly?),
                propertyInfo: typeof(Schedule).GetProperty("ActiveUntil", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Schedule).GetField("<ActiveUntil>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);

            var amount = runtimeEntityType.AddProperty(
                "Amount",
                typeof(long?),
                propertyInfo: typeof(Schedule).GetProperty("Amount", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Schedule).GetField("<Amount>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);

            var amountMode = runtimeEntityType.AddProperty(
                "AmountMode",
                typeof(AmountMode),
                propertyInfo: typeof(Schedule).GetProperty("AmountMode", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Schedule).GetField("<AmountMode>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            amountMode.SetSentinelFromProviderValue(0);

            var autoPost = runtimeEntityType.AddProperty(
                "AutoPost",
                typeof(bool),
                propertyInfo: typeof(Schedule).GetProperty("AutoPost", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Schedule).GetField("<AutoPost>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: false);

            var autoPostFrom = runtimeEntityType.AddProperty(
                "AutoPostFrom",
                typeof(DateOnly?),
                propertyInfo: typeof(Schedule).GetProperty("AutoPostFrom", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Schedule).GetField("<AutoPostFrom>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);

            var cancellationDeadline = runtimeEntityType.AddProperty(
                "CancellationDeadline",
                typeof(DateOnly?),
                propertyInfo: typeof(Schedule).GetProperty("CancellationDeadline", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Schedule).GetField("<CancellationDeadline>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);

            var categoryId = runtimeEntityType.AddProperty(
                "CategoryId",
                typeof(Guid?),
                propertyInfo: typeof(Schedule).GetProperty("CategoryId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Schedule).GetField("<CategoryId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);

            var contractEnd = runtimeEntityType.AddProperty(
                "ContractEnd",
                typeof(DateOnly?),
                propertyInfo: typeof(Schedule).GetProperty("ContractEnd", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Schedule).GetField("<ContractEnd>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);

            var contractProvider = runtimeEntityType.AddProperty(
                "ContractProvider",
                typeof(string),
                propertyInfo: typeof(Schedule).GetProperty("ContractProvider", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Schedule).GetField("<ContractProvider>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 200);

            var contractReference = runtimeEntityType.AddProperty(
                "ContractReference",
                typeof(string),
                propertyInfo: typeof(Schedule).GetProperty("ContractReference", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Schedule).GetField("<ContractReference>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100);

            var contractRenews = runtimeEntityType.AddProperty(
                "ContractRenews",
                typeof(bool),
                propertyInfo: typeof(Schedule).GetProperty("ContractRenews", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Schedule).GetField("<ContractRenews>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: false);

            var createdAt = runtimeEntityType.AddProperty(
                "CreatedAt",
                typeof(DateTimeOffset),
                propertyInfo: typeof(Schedule).GetProperty("CreatedAt", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Schedule).GetField("<CreatedAt>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueConverter: new UtcTicksDateTimeOffsetConverter());
            createdAt.SetSentinelFromProviderValue(0L);

            var icon = runtimeEntityType.AddProperty(
                "Icon",
                typeof(string),
                propertyInfo: typeof(Schedule).GetProperty("Icon", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Schedule).GetField("<Icon>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 64);

            var kind = runtimeEntityType.AddProperty(
                "Kind",
                typeof(EntryKind),
                propertyInfo: typeof(Schedule).GetProperty("Kind", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Schedule).GetField("<Kind>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            kind.SetSentinelFromProviderValue(0);

            var name = runtimeEntityType.AddProperty(
                "Name",
                typeof(string),
                propertyInfo: typeof(Schedule).GetProperty("Name", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Schedule).GetField("<Name>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 200);

            var note = runtimeEntityType.AddProperty(
                "Note",
                typeof(string),
                propertyInfo: typeof(Schedule).GetProperty("Note", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Schedule).GetField("<Note>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 4000);

            var pausedFrom = runtimeEntityType.AddProperty(
                "PausedFrom",
                typeof(DateOnly?),
                propertyInfo: typeof(Schedule).GetProperty("PausedFrom", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Schedule).GetField("<PausedFrom>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);

            var previousScheduleId = runtimeEntityType.AddProperty(
                "PreviousScheduleId",
                typeof(Guid?),
                propertyInfo: typeof(Schedule).GetProperty("PreviousScheduleId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Schedule).GetField("<PreviousScheduleId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);

            var reminderDaysBefore = runtimeEntityType.AddProperty(
                "ReminderDaysBefore",
                typeof(int),
                propertyInfo: typeof(Schedule).GetProperty("ReminderDaysBefore", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Schedule).GetField("<ReminderDaysBefore>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);

            var reminderEnabled = runtimeEntityType.AddProperty(
                "ReminderEnabled",
                typeof(bool),
                propertyInfo: typeof(Schedule).GetProperty("ReminderEnabled", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Schedule).GetField("<ReminderEnabled>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: false);

            var reminderOnDueDate = runtimeEntityType.AddProperty(
                "ReminderOnDueDate",
                typeof(bool),
                propertyInfo: typeof(Schedule).GetProperty("ReminderOnDueDate", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Schedule).GetField("<ReminderOnDueDate>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: false);

            var reminderTime = runtimeEntityType.AddProperty(
                "ReminderTime",
                typeof(TimeOnly),
                propertyInfo: typeof(Schedule).GetProperty("ReminderTime", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Schedule).GetField("<ReminderTime>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: new TimeOnly(0, 0, 0));

            var reviewDate = runtimeEntityType.AddProperty(
                "ReviewDate",
                typeof(DateOnly?),
                propertyInfo: typeof(Schedule).GetProperty("ReviewDate", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Schedule).GetField("<ReviewDate>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);

            var state = runtimeEntityType.AddProperty(
                "State",
                typeof(ScheduleState),
                propertyInfo: typeof(Schedule).GetProperty("State", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Schedule).GetField("<State>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            state.SetSentinelFromProviderValue(0);

            var toAccountId = runtimeEntityType.AddProperty(
                "ToAccountId",
                typeof(Guid?),
                propertyInfo: typeof(Schedule).GetProperty("ToAccountId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Schedule).GetField("<ToAccountId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);

            var toAmount = runtimeEntityType.AddProperty(
                "ToAmount",
                typeof(long?),
                propertyInfo: typeof(Schedule).GetProperty("ToAmount", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Schedule).GetField("<ToAmount>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);

            var updatedAt = runtimeEntityType.AddProperty(
                "UpdatedAt",
                typeof(DateTimeOffset),
                propertyInfo: typeof(Schedule).GetProperty("UpdatedAt", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Schedule).GetField("<UpdatedAt>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueConverter: new UtcTicksDateTimeOffsetConverter());
            updatedAt.SetSentinelFromProviderValue(0L);

            var key = runtimeEntityType.AddKey(
                new[] { id });
            runtimeEntityType.SetPrimaryKey(key);

            var index = runtimeEntityType.AddIndex(
                new[] { accountId });

            var index0 = runtimeEntityType.AddIndex(
                new[] { categoryId });

            var index1 = runtimeEntityType.AddIndex(
                new[] { toAccountId });

            return runtimeEntityType;
        }

        public static RuntimeForeignKey CreateForeignKey1(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType)
        {
            var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("AccountId") },
                principalEntityType.FindKey(new[] { principalEntityType.FindProperty("Id") }),
                principalEntityType,
                deleteBehavior: DeleteBehavior.Restrict,
                required: true);

            return runtimeForeignKey;
        }

        public static RuntimeForeignKey CreateForeignKey2(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType)
        {
            var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("CategoryId") },
                principalEntityType.FindKey(new[] { principalEntityType.FindProperty("Id") }),
                principalEntityType,
                deleteBehavior: DeleteBehavior.Restrict);

            return runtimeForeignKey;
        }

        public static RuntimeForeignKey CreateForeignKey3(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType)
        {
            var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("ToAccountId") },
                principalEntityType.FindKey(new[] { principalEntityType.FindProperty("Id") }),
                principalEntityType,
                deleteBehavior: DeleteBehavior.Restrict);

            return runtimeForeignKey;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", null);
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "Schedules");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
