// <auto-generated />
using System;
using System.Reflection;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Vafadar.Zanance.Core.Commerce;
using Vafadar.Zanance.Data.Commerce;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Vafadar.Zanance.Data.CompiledModel
{
    [EntityFrameworkInternal]
    public partial class StoredResourceSelectionEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "Vafadar.Zanance.Data.Commerce.StoredResourceSelection",
                typeof(StoredResourceSelection),
                baseEntityType,
                propertyCount: 5,
                keyCount: 1);

            var kind = runtimeEntityType.AddProperty(
                "Kind",
                typeof(QuotaKind),
                propertyInfo: typeof(StoredResourceSelection).GetProperty("Kind", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(StoredResourceSelection).GetField("<Kind>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                afterSaveBehavior: PropertySaveBehavior.Throw);
            kind.SetSentinelFromProviderValue(0);

            var scopeKind = runtimeEntityType.AddProperty(
                "ScopeKind",
                typeof(QuotaScopeKind),
                propertyInfo: typeof(StoredResourceSelection).GetProperty("ScopeKind", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(StoredResourceSelection).GetField("<ScopeKind>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                afterSaveBehavior: PropertySaveBehavior.Throw);
            scopeKind.SetSentinelFromProviderValue(0);

            var scopeId = runtimeEntityType.AddProperty(
                "ScopeId",
                typeof(Guid),
                propertyInfo: typeof(StoredResourceSelection).GetProperty("ScopeId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(StoredResourceSelection).GetField("<ScopeId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                afterSaveBehavior: PropertySaveBehavior.Throw,
                sentinel: new Guid("00000000-0000-0000-0000-000000000000"));

            var identitySet = runtimeEntityType.AddProperty(
                "IdentitySet",
                typeof(string),
                propertyInfo: typeof(StoredResourceSelection).GetProperty("IdentitySet", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(StoredResourceSelection).GetField("<IdentitySet>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 8447);

            var revision = runtimeEntityType.AddProperty(
                "Revision",
                typeof(Guid),
                propertyInfo: typeof(StoredResourceSelection).GetProperty("Revision", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(StoredResourceSelection).GetField("<Revision>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                concurrencyToken: true,
                sentinel: new Guid("00000000-0000-0000-0000-000000000000"));

            var key = runtimeEntityType.AddKey(
                new[] { kind, scopeKind, scopeId });
            runtimeEntityType.SetPrimaryKey(key);

            return runtimeEntityType;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", null);
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "ResourceSelections");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
