// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Vafadar.Zanance.Data;
using Vafadar.Zanance.Data.CompiledModel;

#pragma warning disable 219, 612, 618
#nullable disable

[assembly: DbContextModel(typeof(ZananceDbContext), typeof(ZananceDbContextModel))]
