// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Vafadar.Zanance.Data.CompiledModel
{
    public partial class ZananceDbContextModel
    {
        private ZananceDbContextModel()
            : base(skipDetectChanges: false, modelId: new Guid("cdd28b20-8cc6-4e83-8c31-5584d36f18d2"), entityTypeCount: 22)
        {
        }

        partial void Initialize()
        {
            var account = AccountEntityType.Create(this);
            var budget = BudgetEntityType.Create(this);
            var budgetCategoryLimit = BudgetCategoryLimitEntityType.Create(this);
            var category = CategoryEntityType.Create(this);
            var categoryRule = CategoryRuleEntityType.Create(this);
            var contributionPlan = ContributionPlanEntityType.Create(this);
            var recurrenceRule = RecurrenceRuleEntityType.Create(this);
            var goal = GoalEntityType.Create(this);
            var goalAllocation = GoalAllocationEntityType.Create(this);
            var assetEvent = AssetEventEntityType.Create(this);
            var assetLocation = AssetLocationEntityType.Create(this);
            var assetType = AssetTypeEntityType.Create(this);
            var assetValuation = AssetValuationEntityType.Create(this);
            var entryAttachment = EntryAttachmentEntityType.Create(this);
            var entryTemplate = EntryTemplateEntityType.Create(this);
            var ledgerEntry = LedgerEntryEntityType.Create(this);
            var savedFilter = SavedFilterEntityType.Create(this);
            var occurrenceState = OccurrenceStateEntityType.Create(this);
            var schedule = ScheduleEntityType.Create(this);
            var recurrenceRule0 = RecurrenceRule0EntityType.Create(this);
            var exchangeRate = ExchangeRateEntityType.Create(this);
            var zananceSettings = ZananceSettingsEntityType.Create(this);

            BudgetCategoryLimitEntityType.CreateForeignKey1(budgetCategoryLimit, budget);
            CategoryEntityType.CreateForeignKey1(category, category);
            ContributionPlanEntityType.CreateForeignKey1(contributionPlan, goal);
            RecurrenceRuleEntityType.CreateForeignKey1(recurrenceRule, contributionPlan);
            GoalEntityType.CreateForeignKey1(goal, account);
            AssetEventEntityType.CreateForeignKey1(assetEvent, assetType);
            AssetEventEntityType.CreateForeignKey2(assetEvent, assetLocation);
            AssetEventEntityType.CreateForeignKey3(assetEvent, assetLocation);
            AssetValuationEntityType.CreateForeignKey1(assetValuation, assetType);
            LedgerEntryEntityType.CreateForeignKey1(ledgerEntry, account);
            LedgerEntryEntityType.CreateForeignKey2(ledgerEntry, category);
            LedgerEntryEntityType.CreateForeignKey3(ledgerEntry, ledgerEntry);
            LedgerEntryEntityType.CreateForeignKey4(ledgerEntry, account);
            OccurrenceStateEntityType.CreateForeignKey1(occurrenceState, schedule);
            ScheduleEntityType.CreateForeignKey1(schedule, account);
            ScheduleEntityType.CreateForeignKey2(schedule, category);
            ScheduleEntityType.CreateForeignKey3(schedule, account);
            RecurrenceRule0EntityType.CreateForeignKey1(recurrenceRule0, schedule);

            AccountEntityType.CreateAnnotations(account);
            BudgetEntityType.CreateAnnotations(budget);
            BudgetCategoryLimitEntityType.CreateAnnotations(budgetCategoryLimit);
            CategoryEntityType.CreateAnnotations(category);
            CategoryRuleEntityType.CreateAnnotations(categoryRule);
            ContributionPlanEntityType.CreateAnnotations(contributionPlan);
            RecurrenceRuleEntityType.CreateAnnotations(recurrenceRule);
            GoalEntityType.CreateAnnotations(goal);
            GoalAllocationEntityType.CreateAnnotations(goalAllocation);
            AssetEventEntityType.CreateAnnotations(assetEvent);
            AssetLocationEntityType.CreateAnnotations(assetLocation);
            AssetTypeEntityType.CreateAnnotations(assetType);
            AssetValuationEntityType.CreateAnnotations(assetValuation);
            EntryAttachmentEntityType.CreateAnnotations(entryAttachment);
            EntryTemplateEntityType.CreateAnnotations(entryTemplate);
            LedgerEntryEntityType.CreateAnnotations(ledgerEntry);
            SavedFilterEntityType.CreateAnnotations(savedFilter);
            OccurrenceStateEntityType.CreateAnnotations(occurrenceState);
            ScheduleEntityType.CreateAnnotations(schedule);
            RecurrenceRule0EntityType.CreateAnnotations(recurrenceRule0);
            ExchangeRateEntityType.CreateAnnotations(exchangeRate);
            ZananceSettingsEntityType.CreateAnnotations(zananceSettings);

            AddAnnotation("ProductVersion", "10.0.12");
        }
    }
}
