// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Vafadar.Zanance.Data.CompiledModel
{
    public partial class ZananceDbContextModel
    {
        private ZananceDbContextModel()
            : base(skipDetectChanges: false, modelId: new Guid("279e93e6-53d9-44b1-addf-e750aec16406"), entityTypeCount: 16)
        {
        }

        partial void Initialize()
        {
            var account = AccountEntityType.Create(this);
            var budget = BudgetEntityType.Create(this);
            var budgetCategoryLimit = BudgetCategoryLimitEntityType.Create(this);
            var category = CategoryEntityType.Create(this);
            var categoryRule = CategoryRuleEntityType.Create(this);
            var goal = GoalEntityType.Create(this);
            var goalAllocation = GoalAllocationEntityType.Create(this);
            var entryAttachment = EntryAttachmentEntityType.Create(this);
            var entryTemplate = EntryTemplateEntityType.Create(this);
            var ledgerEntry = LedgerEntryEntityType.Create(this);
            var savedFilter = SavedFilterEntityType.Create(this);
            var occurrenceState = OccurrenceStateEntityType.Create(this);
            var recurrenceRule = RecurrenceRuleEntityType.Create(this);
            var schedule = ScheduleEntityType.Create(this);
            var exchangeRate = ExchangeRateEntityType.Create(this);
            var zananceSettings = ZananceSettingsEntityType.Create(this);

            BudgetCategoryLimitEntityType.CreateForeignKey1(budgetCategoryLimit, budget);
            CategoryEntityType.CreateForeignKey1(category, category);
            LedgerEntryEntityType.CreateForeignKey1(ledgerEntry, account);
            LedgerEntryEntityType.CreateForeignKey2(ledgerEntry, category);
            LedgerEntryEntityType.CreateForeignKey3(ledgerEntry, ledgerEntry);
            LedgerEntryEntityType.CreateForeignKey4(ledgerEntry, account);
            OccurrenceStateEntityType.CreateForeignKey1(occurrenceState, schedule);
            RecurrenceRuleEntityType.CreateForeignKey1(recurrenceRule, schedule);
            ScheduleEntityType.CreateForeignKey1(schedule, account);
            ScheduleEntityType.CreateForeignKey2(schedule, category);
            ScheduleEntityType.CreateForeignKey3(schedule, account);

            AccountEntityType.CreateAnnotations(account);
            BudgetEntityType.CreateAnnotations(budget);
            BudgetCategoryLimitEntityType.CreateAnnotations(budgetCategoryLimit);
            CategoryEntityType.CreateAnnotations(category);
            CategoryRuleEntityType.CreateAnnotations(categoryRule);
            GoalEntityType.CreateAnnotations(goal);
            GoalAllocationEntityType.CreateAnnotations(goalAllocation);
            EntryAttachmentEntityType.CreateAnnotations(entryAttachment);
            EntryTemplateEntityType.CreateAnnotations(entryTemplate);
            LedgerEntryEntityType.CreateAnnotations(ledgerEntry);
            SavedFilterEntityType.CreateAnnotations(savedFilter);
            OccurrenceStateEntityType.CreateAnnotations(occurrenceState);
            RecurrenceRuleEntityType.CreateAnnotations(recurrenceRule);
            ScheduleEntityType.CreateAnnotations(schedule);
            ExchangeRateEntityType.CreateAnnotations(exchangeRate);
            ZananceSettingsEntityType.CreateAnnotations(zananceSettings);

            AddAnnotation("ProductVersion", "10.0.12");
        }
    }
}
