// <auto-generated />
using System;
using System.Reflection;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Vafadar.Core.Domain;
using Vafadar.Data.Conventions;
using Vafadar.Zanance.Core.Budgets;
using Vafadar.Zanance.Core.Settings;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Vafadar.Zanance.Data.CompiledModel
{
    [EntityFrameworkInternal]
    public partial class ZananceSettingsEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "Vafadar.Zanance.Core.Settings.ZananceSettings",
                typeof(ZananceSettings),
                baseEntityType,
                propertyCount: 14,
                keyCount: 1);

            var id = runtimeEntityType.AddProperty(
                "Id",
                typeof(Guid),
                propertyInfo: typeof(Entity).GetProperty("Id", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Entity).GetField("<Id>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueGenerated: ValueGenerated.OnAdd,
                afterSaveBehavior: PropertySaveBehavior.Throw,
                sentinel: new Guid("00000000-0000-0000-0000-000000000000"));

            var appLockEnabled = runtimeEntityType.AddProperty(
                "AppLockEnabled",
                typeof(bool),
                propertyInfo: typeof(ZananceSettings).GetProperty("AppLockEnabled", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ZananceSettings).GetField("<AppLockEnabled>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: false);

            var budgetCalendar = runtimeEntityType.AddProperty(
                "BudgetCalendar",
                typeof(PeriodCalendar),
                propertyInfo: typeof(ZananceSettings).GetProperty("BudgetCalendar", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ZananceSettings).GetField("<BudgetCalendar>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            budgetCalendar.SetSentinelFromProviderValue(0);

            var createdAt = runtimeEntityType.AddProperty(
                "CreatedAt",
                typeof(DateTimeOffset),
                propertyInfo: typeof(ZananceSettings).GetProperty("CreatedAt", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ZananceSettings).GetField("<CreatedAt>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueConverter: new UtcTicksDateTimeOffsetConverter());
            createdAt.SetSentinelFromProviderValue(0L);

            var defaultAccountId = runtimeEntityType.AddProperty(
                "DefaultAccountId",
                typeof(Guid?),
                propertyInfo: typeof(ZananceSettings).GetProperty("DefaultAccountId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ZananceSettings).GetField("<DefaultAccountId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);

            var fortnightStart = runtimeEntityType.AddProperty(
                "FortnightStart",
                typeof(DateOnly?),
                propertyInfo: typeof(ZananceSettings).GetProperty("FortnightStart", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ZananceSettings).GetField("<FortnightStart>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);

            var mode = runtimeEntityType.AddProperty(
                "Mode",
                typeof(ExperienceMode),
                propertyInfo: typeof(ZananceSettings).GetProperty("Mode", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ZananceSettings).GetField("<Mode>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            mode.SetSentinelFromProviderValue(0);

            var monthStartDay = runtimeEntityType.AddProperty(
                "MonthStartDay",
                typeof(int),
                propertyInfo: typeof(ZananceSettings).GetProperty("MonthStartDay", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ZananceSettings).GetField("<MonthStartDay>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);

            var notificationsShowDetails = runtimeEntityType.AddProperty(
                "NotificationsShowDetails",
                typeof(bool),
                propertyInfo: typeof(ZananceSettings).GetProperty("NotificationsShowDetails", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ZananceSettings).GetField("<NotificationsShowDetails>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: false);

            var onboardingCompleted = runtimeEntityType.AddProperty(
                "OnboardingCompleted",
                typeof(bool),
                propertyInfo: typeof(ZananceSettings).GetProperty("OnboardingCompleted", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ZananceSettings).GetField("<OnboardingCompleted>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: false);

            var reminderDaysBefore = runtimeEntityType.AddProperty(
                "ReminderDaysBefore",
                typeof(int),
                propertyInfo: typeof(ZananceSettings).GetProperty("ReminderDaysBefore", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ZananceSettings).GetField("<ReminderDaysBefore>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);

            var reminderTime = runtimeEntityType.AddProperty(
                "ReminderTime",
                typeof(TimeOnly),
                propertyInfo: typeof(ZananceSettings).GetProperty("ReminderTime", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ZananceSettings).GetField("<ReminderTime>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: new TimeOnly(0, 0, 0));

            var reportCurrencyCode = runtimeEntityType.AddProperty(
                "ReportCurrencyCode",
                typeof(string),
                propertyInfo: typeof(ZananceSettings).GetProperty("ReportCurrencyCode", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ZananceSettings).GetField("<ReportCurrencyCode>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 3);

            var updatedAt = runtimeEntityType.AddProperty(
                "UpdatedAt",
                typeof(DateTimeOffset),
                propertyInfo: typeof(ZananceSettings).GetProperty("UpdatedAt", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ZananceSettings).GetField("<UpdatedAt>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueConverter: new UtcTicksDateTimeOffsetConverter());
            updatedAt.SetSentinelFromProviderValue(0L);

            var key = runtimeEntityType.AddKey(
                new[] { id });
            runtimeEntityType.SetPrimaryKey(key);

            return runtimeEntityType;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", null);
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "Settings");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
